Ap2 assgoal debounce
tl-its-umich-edu/my-learning-analytics pull request #1181
Opened 2020-12-18 16:22 UTC by chrisrrowland

Fixes #1106 

Another attempt to do this and have it jive with event logging.

2020-12-18 16:23 UTC, chrisrrowland commented on assets/src/components/AssignmentTable.js
> +  const shouldScrollToCurrentWeek = useRef(true)
Given the name I thought this made more sense to use this way.
Not directly related to this functionality.

2020-12-18 16:35 UTC, pushyamig commented
I will review this now

2020-12-18 16:41 UTC, pushyamig commented
I see that assignment goal grade is setting 3 decimal digits? is that intentional, since I did not notice that before

2020-12-18 16:45 UTC, pushyamig commented
Assignment Lock state needs to be preserved when user changes assignment goal, currently it is not.

https://user-images.githubusercontent.com/8579775/102639052-773d4980-4126-11eb-92b9-aa30f3fbac5d.mov

2020-12-18 17:25 UTC, pushyamig requested changes
https://github.com/tl-its-umich-edu/my-learning-analytics/pull/1181#issuecomment-748197941

2021-01-19 22:01 UTC, justin0022 commented
@chrisrrowland should this PR be closed? I see there's `ap2_assignment_goal_debounce` and `ap2_assgoal_debounce` (this PR is from the latter branch).

2021-01-20 18:26 UTC, closed without merging