Fixes #1261 - Removing code for backward compatiblity of SameSite for Django prior to 3.1
tl-its-umich-edu/my-learning-analytics pull request #1263
Opened 2021-04-16 21:02 UTC by jonespm

2021-04-26 19:09 UTC, lsloan requested changes

2021-04-26 19:09 UTC, lsloan commented on requirements.txt
> +PyLTI1p3==1.8.6
Is it necessary to upgrade `PyLTI1p3`?

2021-04-28 21:09 UTC, zqian approved these changes
Verified working with Canvas beta server.

2021-04-29 15:10 UTC, lsloan approved these changes
@jonespm responded to my question.  I'm satisfied with the rest of the PR.

2021-04-29 15:11 UTC, merged