Fixes #1420: clean up names in models
tl-its-umich-edu/my-learning-analytics pull request #1586
Opened 2024-06-28 14:56 UTC by jxiao21

Fixes #1420
Removed verbose names that automatically match and thus don't affect UI
Added help text in Name, Start/End Date, and Data Last Updated
Could use feedback on which potential verbose names could be renamed and to what

2024-07-01 14:35 UTC, jonespm commented on dashboard/models.py
>      canvas_id = models.BigIntegerField(verbose_name="Canvas Id")
This name could be Canvas Academic Term Id

2024-07-01 14:37 UTC, jonespm commented on dashboard/models.py
>      id = models.BigIntegerField(primary_key=True, verbose_name="Term Id")
This should be "Academic Term Id"

2024-07-10 20:12 UTC, jonespm requested changes
These changes to the models seem good to me.

Can you provide the migration for this?

```
docker exec -it student_dashboard /bin/bash
./manage.py  makemigrations
```

Then you should have a new file there you can add to this.

2024-07-10 20:25 UTC, jxiao21 commented
> These changes to the models seem good to me.
> 
> Can you provide the migration for this?
> 
> ```
> docker exec -it student_dashboard /bin/bash
> ./manage.py  makemigrations
> ```
> 
> Then you should have a new file there you can add to this.

Is that the command I need to run in the terminal?

2024-07-10 20:29 UTC, jxiao21 commented
If so, this is what comes up:
`root@27c69b6c5aff:/code# `
And I have to enter something in which I'm not sure what to enter in.

2024-07-11 20:23 UTC, jonespm commented
> If so, this is what comes up: `root@27c69b6c5aff:/code# ` And I have to enter something in which I'm not sure what to enter in.

Yeah when that comes up run

`./manage.py  makemigrations
`

2024-07-19 15:08 UTC, jonespm approved these changes

2024-07-19 15:08 UTC, merged